# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flixterr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flixterr
  pod "AlamofireImage"

  target 'FlixterrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlixterrUITests' do
    # Pods for testing
  end

end
